# Generated by Django 4.0.2 on 2022-07-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paying', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('PLN', 'PLN'), ('GBP', 'GBP')], max_length=3),
        ),
    ]
