# Generated by Django 4.2 on 2023-05-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
    ]
